package com.example.testingdao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CASE.
 */
public class Case {

    private Long id;
    private String name;
    private String caseType;

    public Case() {
    }

    public Case(Long id) {
        this.id = id;
    }

    public Case(Long id, String name, String caseType) {
        this.id = id;
        this.name = name;
        this.caseType = caseType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCaseType() {
        return caseType;
    }

    public void setCaseType(String caseType) {
        this.caseType = caseType;
    }

}
