package com.example.testingdao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.testingdao.Logs;

import com.example.testingdao.LogsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig logsDaoConfig;

    private final LogsDao logsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        logsDaoConfig = daoConfigMap.get(LogsDao.class).clone();
        logsDaoConfig.initIdentityScope(type);

        logsDao = new LogsDao(logsDaoConfig, this);

        registerDao(Logs.class, logsDao);
    }
    
    public void clear() {
        logsDaoConfig.getIdentityScope().clear();
    }

    public LogsDao getLogsDao() {
        return logsDao;
    }

}
