package com.example.lawyerapp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CASES.
 */
public class Cases {

    private Long id;
    private String name;
    private String casetype;

    public Cases() {
    }

    public Cases(Long id) {
        this.id = id;
    }

    public Cases(Long id, String name, String casetype) {
        this.id = id;
        this.name = name;
        this.casetype = casetype;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCasetype() {
        return casetype;
    }

    public void setCasetype(String casetype) {
        this.casetype = casetype;
    }

}
