package com.example.lawyerapp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOGS.
 */
public class Logs {

    private Long id;
    private java.util.Date date;
    private String notes;
    private Float expenses;
    private Float mileage;
    private Float hours;

    public Logs() {
    }

    public Logs(Long id) {
        this.id = id;
    }

    public Logs(Long id, java.util.Date date, String notes, Float expenses, Float mileage, Float hours) {
        this.id = id;
        this.date = date;
        this.notes = notes;
        this.expenses = expenses;
        this.mileage = mileage;
        this.hours = hours;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Float getExpenses() {
        return expenses;
    }

    public void setExpenses(Float expenses) {
        this.expenses = expenses;
    }

    public Float getMileage() {
        return mileage;
    }

    public void setMileage(Float mileage) {
        this.mileage = mileage;
    }

    public Float getHours() {
        return hours;
    }

    public void setHours(Float hours) {
        this.hours = hours;
    }

}
